# User Data Mocking: Predicting the Success Rate of Getting an Immediate Response and Waiting Time to Get an Appointment

### How long do people have to wait until they can get the first appointment with a therapist on Theraply app? Will therapists reply to the user when there are so many other users seeking for help too? 

### We will predict the probability of users getting an immediate response from our therapists and the average waiting time based on therapists they choose. In this notebook, we created a mock data of the number of other users on our app currently contacting the therapists and a list of therapists contacted by a user named 'Mr. A' in Berlin, who speaks only English, is having anxiety symptomps, and looking for a therapist who accepts GKV/public insurance payment.

In [105]:
import pandas as pd
import random

In [107]:
df = pd.read_csv('/Users/tikaramadhini/Documents/theraplydata/thedata/final list of therapists and other info.csv', encoding_errors='ignore', sep=';', index_col='Number')

In [173]:
df.head(3)

,Name,Gender,PersonalTherapy,Group Therapy,Language,TypeOfTherapy,Expertise,Insurance,PatientType,Address,PostalCode,PhoneNumber,Email,Website,CallAvailability,BarrierFreeAccess,WaitingTime(Weeks)
Number,,,,,,,,,,,,,,,,,
1,Prof.Dr.Dr. Rainer Kaus,Male,Yes,Yes,"German, English, Hebrew, Arabic","analytical psychotherapy, depth psychology-bas...","Depression, Panic Attack, Burnout, Crisis Inte...","Public, Private","Adult, Kids and Teenagers",Garnisonkirchplatz 2/II,10178,030 24727950,NaN,NaN,Monday 15.00-16.40,Yes,4
2,Dr. Hannsi Padberg,Female,Yes,Yes,German,depth psychology-based psychotherapie,"Depression, Panic Attack, Burnout, Crisis Inte...","Public, Private","Adult, Kids and Teenagers",Garnisonkirchplatz 2/II,10178,030 24727950,NaN,NaN,Monday 15.00-16.40,Yes,2
3,Dipl.-Psych. Reiner Domes-Nontasila,Male,Yes,No,"German, English",depth psychology-based psychotherapie,"fear - phobia, depression, eating disorder, em...","Public, Private",Adult,Dircksenstrae 47,10178,030 55494880,NaN,NaN,"Monday 14:10 - 15:00, Tuesday 08:10 - 09:00, W...",No,5

### At the moment, there are a lot users contacting our therapists at the same time on the app. Below is a mock, randomized-data of number of other users selecting each therapist.

In [169]:
OtherUsers = [random.randint(1,15) for x in range(130)]
print(OtherUsers)

[10, 14, 14, 14, 12, 14, 12, 10, 11, 2, 13, 10, 10, 8, 4, 6, 1, 7, 1, 10, 3, 3, 15, 5, 11, 10, 7, 2, 10, 15, 10, 14, 14, 7, 4, 11, 12, 1, 8, 8, 3, 10, 12, 9, 9, 4, 5, 9, 4, 7, 5, 11, 1, 4, 8, 3, 8, 15, 7, 12, 14, 6, 8, 1, 8, 12, 14, 3, 5, 2, 2, 7, 4, 4, 2, 7, 11, 7, 3, 10, 5, 3, 11, 3, 10, 11, 4, 4, 14, 15, 5, 8, 4, 14, 2, 3, 1, 5, 13, 8, 14, 6, 6, 10, 8, 14, 1, 14, 1, 13, 5, 14, 8, 12, 8, 6, 14, 12, 6, 2, 14, 3, 14, 8, 11, 12, 9, 8, 3, 8]

In [157]:
df1 = df[["Name", "WaitingTime(Weeks)"]]
df1.set_index("Name")
df1

                                       Name WaitingTime(Weeks)
Number
1                   Prof.Dr.Dr. Rainer Kaus                  4
2                        Dr. Hannsi Padberg                  2
3       Dipl.-Psych. Reiner Domes-Nontasila                  5
4                        Dr. Walter Raffauf                  6
5                Dipl.-Psych. Frank Taffelt                  8
...                                     ...                ...
126                Prof. Dr.Benigna Gerisch                  4
127                Dipl. Soz.Sylvie Tappert                  1
128                            Boris Laaser                  1
129                           Steffen Arndt                  0
130                        Dr.Martyn Vilain                  4

[130 rows x 2 columns]

In [170]:
df1['OtherUsers'] = OtherUsers
df1

/var/folders/9w/mgng1pnn7gj2vt8hz4gb80l40000gn/T/ipykernel_81085/2477990654.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['OtherUsers'] = OtherUsers

                                       Name WaitingTime(Weeks)  OtherUsers
Number
1                   Prof.Dr.Dr. Rainer Kaus                  4          10
2                        Dr. Hannsi Padberg                  2          14
3       Dipl.-Psych. Reiner Domes-Nontasila                  5          14
4                        Dr. Walter Raffauf                  6          14
5                Dipl.-Psych. Frank Taffelt                  8          12
...                                     ...                ...         ...
126                Prof. Dr.Benigna Gerisch                  4          12
127                Dipl. Soz.Sylvie Tappert                  1           9
128                            Boris Laaser                  1           8
129                           Steffen Arndt                  0           3
130                        Dr.Martyn Vilain                  4           8

[130 rows x 3 columns]

In [172]:
df1.to_csv('mock_model.csv', index=False)

### Filtering search options based on needs for Mr. A

In [41]:
mr_a = (df['Language'].str.contains('English') & df['Insurance'].str.contains('Public') & df['Expertise'].str.contains('Anxiety'))

In [174]:
dfmr_a = df.loc[mr_a, ['Name', 'WaitingTime(Weeks)']]
dfmr_a

                                       Name              WaitingTime(Weeks)
Number
6                          Dr. Petra Zinser                               8
15                   Dr. Tanja Mller-Gttken                               2
16               Dipl.-Psych. Elke Hartmann                              12
19                   Dr. Jens-Armin Stephan  not available for new patients
21            Dipl.-Psych. Zaine Brockmeyer                               4
23             Dipl.-Psych. Monika Englisch                              12
24             Dr. Barbara Struthmann-Glenz                               8
27                       Dr. Wilhelm Brggen                              20
28           Dipl.-Psych. Brigitte vom Hofe  not available for new patients
32                         Dr. Anke Banzhaf                               2
33               Dipl.-Psych. Luise Lamberz                               6
36           Dipl.-Psych. Michele Folchetti                               4
37                    Dr. Daniel Schumacher  not available for new patients
41                Dipl.-Psych. Heika Grning                              10
46               Dipl.-Med. Katharina Bolze                               8
47                       Dr. Barbara Costaz                               4
49            Dipl.-Psych. Christiane Khler                               8
52           Dipl.-Psych.So-Rim Jung-Thomas                               4
53                     Dr.Gordian Griffiths                               8
54            M.Sc. M.A.Enno Pfeiffenberger                               4
67      Dipl.-Psych.Alexandra von der Linde                               8

In [67]:
#dropping therapists that are currently unavailable because Mr.A won't contact them
dfmr_a.drop(dfmr_a[dfmr_a['WaitingTime(Weeks)'].str.contains('not available for new patients')].index, inplace=True)
dfmr_a

                                       Name WaitingTime(Weeks)
Number
6                          Dr. Petra Zinser                  8
15                   Dr. Tanja Mller-Gttken                  2
16               Dipl.-Psych. Elke Hartmann                 12
21            Dipl.-Psych. Zaine Brockmeyer                  4
23             Dipl.-Psych. Monika Englisch                 12
24             Dr. Barbara Struthmann-Glenz                  8
27                       Dr. Wilhelm Brggen                 20
32                         Dr. Anke Banzhaf                  2
33               Dipl.-Psych. Luise Lamberz                  6
36           Dipl.-Psych. Michele Folchetti                  4
41                Dipl.-Psych. Heika Grning                 10
46               Dipl.-Med. Katharina Bolze                  8
47                       Dr. Barbara Costaz                  4
49            Dipl.-Psych. Christiane Khler                  8
52           Dipl.-Psych.So-Rim Jung-Thomas                  4
53                     Dr.Gordian Griffiths                  8
54            M.Sc. M.A.Enno Pfeiffenberger                  4
67      Dipl.-Psych.Alexandra von der Linde                  8

### Let's create a mock contacted therapists data by randomly selecting 10 therapists Mr. A would try to contact out of the available therapists list.

In [176]:
selectedtherapists = dfmr_a.sample(n=10)
selectedtherapists.drop('WaitingTime(Weeks)', axis=1, inplace=True)
selectedtherapists

                                  Name
Number
24        Dr. Barbara Struthmann-Glenz
54       M.Sc. M.A.Enno Pfeiffenberger
19              Dr. Jens-Armin Stephan
15              Dr. Tanja Mller-Gttken
16          Dipl.-Psych. Elke Hartmann
21       Dipl.-Psych. Zaine Brockmeyer
49       Dipl.-Psych. Christiane Khler
36      Dipl.-Psych. Michele Folchetti
27                  Dr. Wilhelm Brggen
53                Dr.Gordian Griffiths

In [177]:
selectedtherapists.to_csv('mock_mrAtherapists.csv', index=False)